name: github_action_in_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  args: ^2.5.0
  github_actions_toolkit: ^0.0.8
  lints: ^3.0.0
  test: ^1.24.0
